# -*- coding: utf-8 -*-
"""Linear regression  vaccination checker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LWgevm-k-EgYCKyU2VoN1L2rikosrsz2
"""

#IMPORTING LIBRARIES
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
#READING xlsx  FILES AS PANDAS DATAFRAME
df=pd.read_excel('country_vaccinations.xlsx')
df.head()

#COLLECTING ONLY THE RECORDS OF INDIA
df=df.iloc[1891:1935]

"""As linear regression model cannot accept dates as a parameter, we take days since January 15th as our independent variable ie 2021-01-15(as our data begins from 15th January). Thus, while predicting we will be start from
January 15th. Hence, X will contain values starting from 0, where 0 indicates January 15.

"""

#PREDICTING TOTAL VACCINATIONS USING LINEAR REGRESSION MODEL WITH DATE AS INDEPENDENT VARIABLE
dataset=df
dataset=dataset.iloc[:,2:4]
dataset=dataset.dropna()
dataset.head()

#WE TAKE VACCINATION AS DEPENDENT VARIABLE(Y) AND DATE AS INDEPENDENT VARIABLE(X)
X=pd.DataFrame(np.array(range(0,43))).values
Y=dataset.iloc[:,[1]].values
Y

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=1)
from sklearn.linear_model import LinearRegression
linear=LinearRegression()
linear.fit(X_train,Y_train)

import matplotlib.pyplot as plt
plt.scatter(X_train,Y_train,color='black')
plt.plot(X_train,linear.predict(X_train),color='blue')
plt.show()

import matplotlib.pyplot as plt
plt.scatter(X_test,Y_test,color='red')
plt.plot(X_test,linear.predict(X_test),color='green')
plt.show()

#PRDEICTION DATA FOR MARCH 15TH
linear.predict([[59]])

"""March 15th is 59 days from January 15th(as our data begins from January 15th)"""

print(f'accuraccy is {linear.score(X_test,Y_test)*100}%')